### ISSUE TITLE
AI Search Can't Connect to Azure OpenAI Resource

### ISSUE THREAD

**Issue by sydneybeckcook** [microsoft/sample-app-aoai-chatGPT#1050]
**Describe the bug**
When you send a chat request using AI Seach data, the response is "Outbound network access is restricted. The hostname 'AiSearchResource.search.windows.net' for parameter 'endpoint' is not in the allowed FQDN list for this resource."

**To Reproduce**
1. Connect AI Search and OpenAI resource to webapp 
2. Disable public access
3. Enable private links and shared access between AI Search and Web App, Storage Account and OpenAI resources. 

**Expected behavior**
The chatbot should respond based on the data in the storage account and index in AI Search

**Screenshots**
![image](https://github.com/user-attachments/assets/52e1d1e1-b00a-4656-99bc-2e9fb12ea6d3)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version: gpt-35-turbo 0613
 - Is chat history enabled?: Yes
 - Are you using data? If so, what data source? Azure AI Search
- Verify the startup command and runtime configuration by showing the output of the following az CLI command: python3 -m gunicorn app:app

**Logs**
024-08-13T15:58:50.354687522Z DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
2024-08-13T15:58:50.355308630Z DEBUG:httpx:load_verify_locations cafile='/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/certifi/cacert.pem'
2024-08-13T15:58:50.385017416Z DEBUG:openai._base_client:Request options: {'method': 'post', 'url': '/deployments/gpt-35-turbo/chat/completions', 'headers': {'api-key': 'REDACTED'}, 'files': None, 'json_data': {'messages': [{'role': 'user', 'content': 'What is D1 phase? '}, {'role': 'user', 'content': 'Summarize the conversation so far into a 4-word or less title. Do not use any quotation marks or punctuation. Do not include any other commentary or description.'}], 'model': 'gpt-35-turbo', 'max_tokens': 64, 'temperature': 1}}
2024-08-13T15:58:50.389519275Z DEBUG:httpcore.connection:connect_tcp.started host='REDACTED OAI RESOURCE NAME.openai.azure.com' port=443 local_address=None timeout=5.0 socket_options=None
2024-08-13T15:58:50.401002724Z DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7aa7a3fd84d0>
2024-08-13T15:58:50.401051525Z DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7aa7a3e009e0> server_hostname='REDACTED OAI RESOURCE NAME.openai.azure.com' timeout=5.0
2024-08-13T15:58:50.404978376Z DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7aa7a389e4d0>
2024-08-13T15:58:50.405265779Z DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
2024-08-13T15:58:50.405657285Z DEBUG:httpcore.http11:send_request_headers.complete
2024-08-13T15:58:50.405681885Z DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
2024-08-13T15:58:50.405967189Z DEBUG:httpcore.http11:send_request_body.complete
2024-08-13T15:58:50.406016289Z DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
2024-08-13T15:58:50.546225012Z DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Tue, 13 Aug 2024 15:58:50 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'811'), (b'Connection', b'keep-alive'), (b'Cache-Control', b'no-cache, must-revalidate'), (b'access-control-allow-origin', b'*'), (b'apim-request-id', redacted'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'x-content-type-options', b'nosniff'), (b'x-ms-region', b'East US'), (b'x-ratelimit-remaining-requests', b'349'), (b'x-ratelimit-remaining-tokens', b'349936'), (b'x-ms-rai-invoked', b'true'), (b'x-request-id', b'da8df017-41fc-43b4-9943-1c0af5fb141a'), (b'azureml-model-session', b'turbo-0613-ee42533b'), (b'x-envoy-upstream-service-time', b'117'), (b'x-ms-client-request-id', b'c2140390-1fd9-46f1-b32c-f6ba45fdef09')])
2024-08-13T15:58:50.547169324Z INFO:httpx:HTTP Request: POST https://REDACTED OAI RESOURCE NAME.openai.azure.com//openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 200 OK"
2024-08-13T15:58:50.547403327Z DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
2024-08-13T15:58:50.547656431Z DEBUG:httpcore.http11:receive_response_body.complete
2024-08-13T15:58:50.547886334Z DEBUG:httpcore.http11:response_closed.started
2024-08-13T15:58:50.548085936Z DEBUG:httpcore.http11:response_closed.complete
2024-08-13T15:58:50.548381040Z DEBUG:openai._base_client:HTTP Request: POST https://REDACTED OAI RESOURCE NAME.openai.azure.com//openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-05-01-preview "200 OK"
2024-08-13T15:58:50.928355880Z DEBUG:httpcore.connection:close.started
2024-08-13T15:58:50.928685184Z DEBUG:httpcore.connection:close.complete
2024-08-13T15:58:50.958958378Z INFO:root:Getting token usage for user 02d8070c-6ac3-40e7-bbfd-4031ec2bf264 on date 2024-08-13
2024-08-13T15:58:50.994843345Z INFO:root:Token usage found for user 02d8070c-6ac3-40e7-bbfd-4031ec2bf264 on date 2024-08-13
2024-08-13T15:58:51.030244005Z INFO:root:update_usage_from_message: user_id: 02d8070c-6ac3-40e7-bbfd-4031ec2bf264
2024-08-13T15:58:51.030344506Z INFO:root:update_usage_from_message: tokens: 10
2024-08-13T15:58:51.030391607Z INFO:root:Getting token usage for user 02d8070c-6ac3-40e7-bbfd-4031ec2bf264 on date 2024-08-13
2024-08-13T15:58:51.045933609Z INFO:root:Token usage found for user 02d8070c-6ac3-40e7-bbfd-4031ec2bf264 on date 2024-08-13
2024-08-13T15:58:51.103501357Z DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
2024-08-13T15:58:51.103982263Z DEBUG:httpx:load_verify_locations cafile='/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/certifi/cacert.pem'
2024-08-13T15:58:51.113455387Z DEBUG:openai._base_client:Request options: {'method': 'post', 'url': '/deployments/gpt-35-turbo/chat/completions', 'headers': {'X-Stainless-Raw-Response': 'true', 'api-key': 'REDACTED'}, 'files': None, 'json_data': {'messages': [{'role': 'user', 'content': 'What is D1 phase at Cook Medical? '}], 'model': 'gpt-35-turbo', 'max_tokens': 2000, 'stop': None, 'stream': True, 'temperature': 0.7, 'top_p': 1.0, 'user': None}, 'extra_json': {'data_sources': [{'type': 'azure_search', 'parameters': {'top_n_documents': 3, 'strictness': 2, 'in_scope': False, 'index_name': 'REDACTED', 'semantic_configuration': REDACTED', 'query_type': 'vector_semantic_hybrid', 'endpoint': 'https://REDACTED AI SEARCH RESOURCE NAME.search.windows.net', 'authentication': {'type': 'api_key', 'key': 'REDACTED'}, 'embedding_dependency': {'type': 'deployment_name', 'deployment_name': 'text-embedding-ada-002'}, 'fields_mapping': {'content_fields': ['chunk'], 'title_field': 'title', 'url_field': 'filename', 'filepath_field': 'filename', 'vector_fields': ['vector']}, 'allow_partial_result': False, 'include_contexts': ['citations', 'intent'], 'role_information': 'You are an AI assistant for REDACTED. Assist with document queries and respond to any prompt with helpful and informative answers. Do not apologize if information is unavailable in documents; just answer the question.'}}]}}
2024-08-13T15:58:51.114362998Z DEBUG:httpcore.connection:connect_tcp.started host='REDACTED OPENAI RESOURCE NAME.openai.azure.com' port=443 local_address=None timeout=5.0 socket_options=None
2024-08-13T15:58:51.121575492Z DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7aa7a38fdad0>
2024-08-13T15:58:51.121617793Z DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7aa7a3e009e0> server_hostname='cai-bot002.openai.azure.com' timeout=5.0
2024-08-13T15:58:51.124485030Z DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7aa7a38fd590>
2024-08-13T15:58:51.124838435Z DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
2024-08-13T15:58:51.125183139Z DEBUG:httpcore.http11:send_request_headers.complete
2024-08-13T15:58:51.125203039Z DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
2024-08-13T15:58:51.125556444Z DEBUG:httpcore.http11:send_request_body.complete
2024-08-13T15:58:51.125577144Z DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
2024-08-13T15:58:51.230137404Z DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 400, b'Bad Request', [(b'Date', b'Tue, 13 Aug 2024 15:58:51 GMT'), (b'Content-Type', b'application/json; charset=UTF-8'), (b'Content-Length', b'264'), (b'Connection', b'keep-alive'), (b'x-envoy-upstream-service-time', b'79'), (b'apim-request-id', b'8da869cc-4215-40d2-b2f0-392a4c54dfa7'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'x-content-type-options', b'nosniff'), (b'x-ms-region', b'East US'), (b'x-ratelimit-remaining-requests', b'348'), (b'x-ratelimit-remaining-tokens', b'347936')])
2024-08-13T15:58:51.230615810Z INFO:httpx:HTTP Request: POST https://REDACTED OPENAI RESOURCE NAME.openai.azure.com//openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 400 Bad Request"
2024-08-13T15:58:51.230640710Z DEBUG:openai._base_client:HTTP Request: POST https://REDACTED OPENAI RESOURCE NAME.openai.azure.com//openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-05-01-preview "400 Bad Request"
2024-08-13T15:58:51.231827226Z DEBUG:openai._base_client:Encountered httpx.HTTPStatusError
2024-08-13T15:58:51.231850426Z Traceback (most recent call last):
2024-08-13T15:58:51.231855726Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1599, in _request
2024-08-13T15:58:51.231860526Z     response.raise_for_status()
2024-08-13T15:58:51.232042428Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
2024-08-13T15:58:51.232052229Z     raise HTTPStatusError(message, request=request, response=self)
2024-08-13T15:58:51.232056629Z httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://REDACTED OPENAI RESOURCE NAME.openai.azure.com//openai/deployments/gpt-35-turbo/chat/completions?api-version=2024-05-01-preview'
2024-08-13T15:58:51.232061229Z For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
2024-08-13T15:58:51.232067929Z DEBUG:openai._base_client:Not retrying
2024-08-13T15:58:51.232072129Z DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
2024-08-13T15:58:51.232352732Z DEBUG:httpcore.http11:receive_response_body.complete
2024-08-13T15:58:51.232366033Z DEBUG:httpcore.http11:response_closed.started
2024-08-13T15:58:51.232965940Z DEBUG:httpcore.http11:response_closed.complete
2024-08-13T15:58:51.232982741Z DEBUG:openai._base_client:Re-raising status error
2024-08-13T15:58:51.234235257Z ERROR:root:Exception in send_chat_request
2024-08-13T15:58:51.234254257Z Traceback (most recent call last):
2024-08-13T15:58:51.234273257Z   File "/tmp/8dcbba4ca0a7306/app.py", line 579, in send_chat_request
2024-08-13T15:58:51.234281157Z     raw_response = await azure_openai_client.chat.completions.with_raw_response.create(**model_args)
2024-08-13T15:58:51.234286958Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.234292358Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/_legacy_response.py", line 353, in wrapped
2024-08-13T15:58:51.234298258Z     return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
2024-08-13T15:58:51.234303958Z                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.234309758Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1289, in create
2024-08-13T15:58:51.234326358Z     return await self._post(
2024-08-13T15:58:51.234330658Z            ^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.234335658Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1826, in post
2024-08-13T15:58:51.234341758Z     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
2024-08-13T15:58:51.234350758Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.234354458Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1519, in request
2024-08-13T15:58:51.234357958Z     return await self._request(
2024-08-13T15:58:51.234361259Z            ^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.234364559Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1620, in _request
2024-08-13T15:58:51.234367959Z     raise self._make_status_error_from_response(err.response) from None
2024-08-13T15:58:51.234371459Z openai.BadRequestError: Error code: 400 - {'error': {'requestid': '8da869cc-4215-40d2-b2f0-392a4c54dfa7', 'code': 400, 'message': "Outbound network access is restricted. The hostname 'REDACTED AI SEARCH RESOURCE NAME.search.windows.net' for parameter 'endpoint' is not in the allowed FQDN list for this resource."}}
2024-08-13T15:58:51.235422672Z ERROR:root:Error code: 400 - {'error': {'requestid': '8da869cc-4215-40d2-b2f0-392a4c54dfa7', 'code': 400, 'message': "Outbound network access is restricted. The hostname 'REDACTED AI SEARCH RESOURCE NAME.search.windows.net' for parameter 'endpoint' is not in the allowed FQDN list for this resource."}}
2024-08-13T15:58:51.235446973Z Traceback (most recent call last):
2024-08-13T15:58:51.235454073Z   File "/tmp/8dcbba4ca0a7306/app.py", line 724, in conversation_internal
2024-08-13T15:58:51.235461173Z     result = await stream_chat_request(request_body, request_headers)
2024-08-13T15:58:51.235467373Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.235473773Z   File "/tmp/8dcbba4ca0a7306/app.py", line 677, in stream_chat_request
2024-08-13T15:58:51.235479973Z     response, apim_request_id = await send_chat_request(request_body, request_headers)
2024-08-13T15:58:51.235486273Z                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.235492373Z   File "/tmp/8dcbba4ca0a7306/app.py", line 586, in send_chat_request
2024-08-13T15:58:51.235498673Z     raise e
2024-08-13T15:58:51.235504573Z   File "/tmp/8dcbba4ca0a7306/app.py", line 579, in send_chat_request
2024-08-13T15:58:51.235511173Z     raw_response = await azure_openai_client.chat.completions.with_raw_response.create(**model_args)
2024-08-13T15:58:51.235517674Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.235523974Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/_legacy_response.py", line 353, in wrapped
2024-08-13T15:58:51.235541574Z     return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
2024-08-13T15:58:51.235547874Z                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.235552974Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1289, in create
2024-08-13T15:58:51.235558974Z     return await self._post(
2024-08-13T15:58:51.235564774Z            ^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.235570674Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1826, in post
2024-08-13T15:58:51.235577574Z     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
2024-08-13T15:58:51.235584274Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.235591275Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1519, in request
2024-08-13T15:58:51.235598375Z     return await self._request(
2024-08-13T15:58:51.235604875Z            ^^^^^^^^^^^^^^^^^^^^
2024-08-13T15:58:51.235611975Z   File "/tmp/8dcbba4ca0a7306/antenv/lib/python3.11/site-packages/openai/_base_client.py", line 1620, in _request
2024-08-13T15:58:51.235619175Z     raise self._make_status_error_from_response(err.response) from None
2024-08-13T15:58:51.235626075Z openai.BadRequestError: Error code: 400 - {'error': {'requestid': '8da869cc-4215-40d2-b2f0-392a4c54dfa7', 'code': 400, 'message': "Outbound network access is restricted. The hostname 'REDACTED AI SEARCH RESOURCE NAME.search.windows.net' for parameter 'endpoint' is not in the allowed FQDN list for this resource."}}

**Additional context**
This problem suddenly appeared over the weekend without any changes made. We have public access off and our private networking should be fully set up or at least was working previously for months and suddenly stopped working. We have approved shared access between our AI Search and all our resources and sub resources.

**Comment by Krish054** [comment]
@sydneybeckcook Please check if [this doc](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/use-your-data-securely) helps you? Since outbound network access is restricted I suppose you could also try tweaking NSG rules, if you have one in use. I'm no expert but these are my two cents.

**Comment by sydneybeckcook** [comment]
> @sydneybeckcook Please check if [this doc](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/use-your-data-securely) helps you? Since outbound network access is restricted, I suppose you could also try tweaking NSG rules, if you have one in use. I'm no expert but these are my two cents.

Thanks for the link, we did use that document when originally setting up our resources and it had been working for months. We are not using Azure firewall or NSG.
