### ISSUE TITLE
Impossibe to Deploy a Web App in Azure OpenAI studio : An error message 

### ISSUE THREAD

**Issue by azakharovams** [microsoft/sample-app-aoai-chatGPT#1071]
**Describe the bug**
Impossible to deploy to web app, multiple users confirmed that they have the following error message while trying to deploy:
"InvalidTemplate: Deployment template validation failed: 'The value for the template parameter 'azureOpenAIEmbeddingEndpoint' at line '1' and column '4690' is not provided. Please see
https://aka.ms/arm-create-parameter-file
for usage details.'."

**To Reproduce**
Steps to reproduce the behavior in old or new look:
1. Go to Azure Open AI studio
2. Select chat playground
3. Click on Deploy to webapp

**Expected behavior**
It should deploy the app but in the old look, I have the error "InvalidTemplate: Deployment template validation failed: 'The value for the template parameter 'azureOpenAIEmbeddingEndpoint' at line '1' and column '4690' is not provided. Please see
https://aka.ms/arm-create-parameter-file
for usage details.'."
In the  new look, I also have an error but it's not specified.

**Screenshots**
![image](https://github.com/user-attachments/assets/5df2881b-c65f-441d-8dbe-7fdb8836fc4b)
![image](https://github.com/user-attachments/assets/58e9c066-562b-40b6-8424-2a7649d3687a)

**Comment by azakharovams** [comment]
After conducting multiple tests, we've determined that the web app functions properly only when using the updated new interface (look), and your model, web app, and resource group are all located within the same region.

**Comment by dljones555** [comment]
I'm having trouble as well. Switched to new interface. Deployment worked. Says web app is running.

- Entered URL and it just hangs in Edge. 
- Eventually got a 503 service unavailable
- Looked at logs and said service unavailable with free plan
- AZ-102 MS Learn docs for exercise1 say to set as free unavailable. https://learn.microsoft.com/en-us/training/modules/get-started-openai/8-exercise
- I deleted webapp, deployed again with basic plan and get a 504 gateway unavailable.

Can you please look at this? I guess I could deploy a standard plan. :(

Logs in Azure shown below.

2024-08-30T21:49:47.832464576Z: [ERROR]  WARNING:root:No datasource configuration found in the environment -- calls will be made to Azure OpenAI without grounding data.
2024-08-30T21:49:47.878981802Z: [ERROR]  WARNING:root:[{'type': 'missing', 'loc': ('service',), 'msg': 'Field required', 'input': {'top_k': '5', 'strictness': '3', 'enable_in_domain': 'false', 'use_semantic_search': 'false'}, 'url': 'https://errors.pydantic.dev/2.8/v/missing'}, {'type': 'missing', 'loc': ('index',), 'msg': 'Field required', 'input': {'top_k': '5', 'strictness': '3', 'enable_in_domain': 'false', 'use_semantic_search': 'false'}, 'url': 'https://errors.pydantic.dev/2.8/v/missing'}]
2024-08-30T21:49:47.879023904Z: [ERROR]  WARNING:root:[{'type': 'missing', 'loc': ('service',), 'msg': 'Field required', 'input': {'top_k': '5', 'strictness': '3', 'enable_in_domain': 'false', 'use_semantic_search': 'false'}, 'url': 'https://errors.pydantic.dev/2.8/v/missing'}, {'type': 'missing', 'loc': ('index',), 'msg': 'Field required', 'input': {'top_k': '5', 'strictness': '3', 'enable_in_domain': 'false', 'use_semantic_search': 'false'}, 'url': 'https://errors.pydantic.dev/2.8/v/missing'}]
2024-08-30T21:49:47.879032605Z: [ERROR]  WARNING:root:No datasource configuration found in the environment -- calls will be made to Azure OpenAI without grounding data.
2024-08-30T21:49:47.879038405Z: [ERROR]  WARNING:root:[{'type': 'missing', 'loc': ('service',), 'msg': 'Field required', 'input': {'top_k': '5', 'strictness': '3', 'enable_in_domain': 'false', 'use_semantic_search': 'false'}, 'url': 'https://errors.pydantic.dev/2.8/v/missing'}, {'type': 'missing', 'loc': ('index',), 'msg': 'Field required', 'input': {'top_k': '5', 'strictness': '3', 'enable_in_domain': 'false', 'use_semantic_search': 'false'}, 'url': 'https://errors.pydantic.dev/2.8/v/missing'}]
2024-08-30T21:49:48.170732758Z: [ERROR]  [2024-08-30 21:49:48 +0000] [73] [INFO] Started server process [73]
2024-08-30T21:49:48.170775561Z: [ERROR]  [2024-08-30 21:49:48 +0000] [75] [INFO] Started server process [75]
2024-08-30T21:49:48.170781661Z: [ERROR]  [2024-08-30 21:49:48 +0000] [75] [INFO] Waiting for application startup.
2024-08-30T21:49:48.170786161Z: [ERROR]  [2024-08-30 21:49:48 +0000] [73] [INFO] Waiting for application startup.
2024-08-30T21:49:48.170791062Z: [ERROR]  [2024-08-30 21:49:48 +0000] [75] [INFO] Application startup 


-

**Comment by pedropberger** [comment]
Same problem here, only the resource group isn't created in the same region, and I think I have permission to change it.

**Comment by Rmrak** [comment]
Has anyone debugged the issue with deploying web app, i still have this problem "Web App deployment failed
InvalidTemplate: Deployment template validation failed: 'The value for the template parameter 'azureOpenAIEmbeddingEndpoint' at line '1' and column '5094' is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.'."

**Comment by titanlogic** [comment]
I'm having the same issue, very frustrating.

**Comment by guyyardeni** [comment]
Same issue, tried in both new and old interface and all objects are in the same region.

**Comment by mikemishal** [comment]
I am having the same issue with new and old interface.

**Comment by sidharthaprusty** [comment]
Same issue. The stack trace shows the following: 
AxiosError: Request failed with status code 400
    at xY (https://ai.azure.com/assets/index-5f3a7342.js:4777:1233)
    at XMLHttpRequest.z (https://ai.azure.com/assets/index-5f3a7342.js:4777:5907)
    at CV.request (https://ai.azure.com/assets/index-5f3a7342.js:4779:1919)

**Comment by akjaineusanuj** [comment]
I am running into the same issue. I tried with various locations, including EastUS or EastUS2, with combinations of RGs in different ones. Looks like something changed since last week as I was able to deploy. 
I also tried the old/new look with the same issue "azureOpenAIEmbeddingEndpoint is not provided"
Can someone from Microsoft comment and get this fixed, please?
Thank you

**Comment by 2gad** [comment]
I could not take photos as this was on my work laptop but I was facing the same issue and was able to deploy by doing the following - copy the failed PUT request from the network tab, go to postman, add the body (copy the payload from there request in the network tab), grab your bearer token as well and fire off the request
I got a 201

I was also able to verify from the environment variables of my Web App that the deployment was indeed updated (was upgrading from gpt3 to 4-mini)

**Comment by akjaineusanuj** [comment]
wow! The deployment worked using the postman trick with put/bearer token and modifying the "azureOpenAIEmbeddingEndpoint" : {}   to     "azureOpenAIEmbeddingEndpoint" : { "value":""}
 . I got a 201 as well.  Thank you so so much.

**Comment by tatsuyalkameda** [comment]
I tried a similar workaround as follows:

Copy the failed POST request using the "Copy > Copy as cURL (bash)" option in Chrome's developer tools.
Modify the copied cURL command as described above.
Open the Azure Portal, launch the Cloud Shell in bash, paste the modified command, and run it.
However, I received the following error:

"error":{
  "code":"InvalidTemplateDeployment",
  ...
  ,"details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"SubscriptionIsOverQuotaForSku","message":"This region has quota of 0 instances for your subscription. Try selecting different region or SKU."
...  
  
I'm not sure which part of the settings is causing this issue.
Does anyone have any ideas on how to fix or work around this?

**Comment by CStark-1** [comment]
Having the same issue - Must have been changed on Microsofts end - hesitant to try a work around until it has been addressed.

**Comment by 2gad** [comment]
Did anyone try today? Is it fixed?

**Comment by 2gad** [comment]
> I tried a similar workaround as follows:
> 
> 1. Copy the failed POST request using the "Copy > Copy as cURL (bash)" option in Chrome's developer tools.
> 2. Modify the copied cURL command as described above.
> 3. Open the Azure Portal, launch the Cloud Shell in bash, paste the modified command, and run it.
> 
> However, I received the following error:
> 
> "error":{ "code":"InvalidTemplateDeployment", ... ,"details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"SubscriptionIsOverQuotaForSku","message":"This region has quota of 0 instances for your subscription. Try selecting different region or SKU." ...
> 
> I'm not sure which part of the settings is causing this issue. Does anyone have any ideas on how to fix or work around this?

unfortunately I have not seen this before - I would suggest checking the request body is complete

**Comment by gaborvar** [comment]
Just checked again and failed with the same message "InvalidTemplate: Deployment template validation failed: 'The value for the template parameter 'azureOpenAIEmbeddingEndpoint' at line '1' and column '8426'"...
Last and only time it worked for me was on Aug 30 16:40 but I was not able to repeat deployment since then. Tried several combinations of RG, location etc.

**Comment by CStark-1** [comment]
Is this error likely to be resolved or is it worth just using the above workarounds going forward? Seems like an unnecessary amount of steps for a new process.

**Comment by gaborvar** [comment]
> Is this error likely to be resolved or is it worth just using the above workarounds going forward? Seems like an unnecessary amount of steps for a new process.

There is another potential workaround, although I haven't experimented yet. The code is apparently from https://github.com/microsoft/sample-app-aoai-chatGPT.git . One could deploy from there bypassing the deployment template. Not as straightforward as the template sniffing and rectification approach discussed above though.

**Comment by 2gad** [comment]
> Is this error likely to be resolved or is it worth just using the above workarounds going forward? Seems like an unnecessary amount of steps for a new process.

I can't imagine they won't fix it - probably they just don't know about it.. Not sure how to even report it lol

**Comment by 2gad** [comment]
https://github.com/microsoft/sample-app-aoai-chatGPT/discussions/1085

If everyone can upvote this discussion it could help lol! need this fixed asap haha

**Comment by sarah-widder** [comment]
Hi all, the template validation error in the playground deployment flow is a known issue with a fix underway. Apologies for the inconvenience. In the meantime deploying from this repo with the 'deploy to azure' button or the azure CLI are possible workarounds.

**Comment by ouhaddaOualid** [comment]
i used the postman trick and got this error ;
this is the error for now : The template deployment failed with error: 'Authorization failed for template resource '22a25cd7-ed25-5eff-8929-38a526b663dc' of type 'Microsoft.Authorization/roleAssignments'. The client 'OfekProduction@caesarea.com' with object id '6ee952df-0c71-466c-a8f6-174d3b5a2287' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/85902c28-eff5-423a-b460-f53331149 ....
what permissions i need for this ?

**Comment by CStark-1** [comment]
Appears to be fixed.

**Comment by jschmHoBa** [comment]
not fixed for me testing 5 minutes ago in the new Azure AI Studio Env. (All resources set to "West Europe")

**Comment by gaborvar** [comment]
> Appears to be fixed.

No change on my side, unfortunately. I tried with a few combinations of location, RG etc. My successful deployments in the past 10 days were all independent of the Studio.

I also tried the az webapp CLI based deployment as workaround and it works. Not a direct replacement however, but offers more control.

**Comment by sarah-widder** [comment]
@jschmHoBa @gaborvar the fix is making its way to all environments. For now, I believe it is fixed in Azure OpenAI studio, if you use the "old view".

**Comment by tatsuyalkameda** [comment]
Yes, it seems like the bug has been fixed, and the command modification workaround is no longer necessary.

However, I am now directly getting the following error when using the deploy button. This indicates that while the workaround mentioned in my previous post was correct, there are still some issues in my environment.

Any suggestions to fix this?

SubscriptionIsOverQuotaForSku: This region has quota of 0 instances for your subscription. Try selecting different region or SKU.

**Comment by gaborvar** [comment]
> @jschmHoBa @gaborvar the fix is making its way to all environments. For now, I believe it is fixed in Azure OpenAI studio, if you use the "old view".

It works, thank you! (West Europe location, new OpenAI Studio)

**Comment by bmerkle** [comment]
this can be closed
