### ISSUE TITLE
Deployment from Chat Playground fails with 500 - Internal Server Error

### ISSUE THREAD

**Issue by nickcapitoubt** [microsoft/sample-app-aoai-chatGPT#1189]
**Describe the bug**
Deployed to Azure via Chat Playground.  Deployment failed, retried it succeeded but now we get a 500 internal server error when trying to access.

**To Reproduce**
1. Go to the site where it was deployed to azure e.g. <name>.azurewebsites.net
2. See error ![Image](https://github.com/user-attachments/assets/5b3c741b-619e-44d3-aa17-81903cbe2fab)

**Expected behavior**
Once deployment is complete we expect the app to function.

**Screenshots**
![Image](https://github.com/user-attachments/assets/6a7ae9b6-0631-45e8-93f8-6141cf15ac1e)

````

2024-11-26T16:44:10.8045435Z [2024-11-26 16:44:10 +0000] [94] [ERROR] Error handling request /
2024-11-26T16:44:10.8046232Z Traceback (most recent call last):
2024-11-26T16:44:10.8046277Z   File "/tmp/8dd0e37c6b285a1/antenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
2024-11-26T16:44:10.8046303Z     self.handle_request(listener, req, client, addr)
2024-11-26T16:44:10.8046337Z   File "/tmp/8dd0e37c6b285a1/antenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2024-11-26T16:44:10.8046369Z     respiter = self.wsgi(environ, resp.start_response)
````

**Logs**

[log.txt](https://github.com/user-attachments/files/17922879/log.txt)

**Comment by fredejuul** [comment]
I face the same issue

**Comment by guyyardeni** [comment]
I've been able to get around this issue a few times by syncing the repo using Deployment Center.

**Comment by fredejuul** [comment]
@guyyardeni this seems to fix my issue as well. 

Thx

**Comment by kellermatthis** [comment]
Do you have a startup command configured? Make sure the following snipped exists: "python3 -m gunicorn app:app"
![Image](https://github.com/user-attachments/assets/a84dbf9f-1c5a-452b-9c9c-aa67734bdc91)

**Comment by nickcapitoubt** [comment]
@kellermatthis  we do not.![Image](https://github.com/user-attachments/assets/34330caa-45b5-4e0d-8409-dcd234aa39fe)
