### ISSUE TITLE
Error running index creation script - data_utils

### ISSUE THREAD

**Issue by edercarlima** [microsoft/sample-app-aoai-chatGPT#147]
Hi @pamelafox 

When running the index creation script  data_preparation.py  (c:\teste\scripts> python data_preparation.py --config config.json --njobs=4 --form-rec-resource cog-fr-nwnw7w7kl2hg --form-rec-key ***)

It is showing the following error message:
Error:
Traceback (most recent call last):
  File "c:\teste\scripts\data_preparation.py", line 16, in <module>
    from data_utils import chunk_directory
  File "c:\teste\scripts\data_utils.py", line 18, in <module>
    from langchain.text_splitter import MarkdownTextSplitter, RecursiveCharacterTextSplitter, PythonCodeTextSplitter
  File "C:\Users\inovacao\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\inovacao\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "C:\Users\inovacao\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent.py", line 15, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "C:\Users\inovacao\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\agents\agent_iterator.py", line 30, in <module>
    from langchain.tools import BaseTool
  File "C:\Users\inovacao\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\tools\__init__.py", line 77, in <module>
    from langchain.tools.powerbi.tool import (
  File "C:\Users\inovacao\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\tools\powerbi\tool.py", line 12, in <module>
    from langchain.chains.llm import LLMChain
  File "C:\Users\inovacao\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\__init__.py", line 48, in <module>
    from langchain.chains.llm_math.base import LLMMathChain
  File "C:\Users\inovacao\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\llm_math\base.py", line 9, in <module>
    import numexpr
  File "C:\Users\inovacao\AppData\Local\Programs\Python\Python311\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
ImportError: DLL load failed while importing interpreter: The specified module could not be found.
PS c:\teste\scripts> 

Until Thursday of last week, I was running this same script with the same version of python and it wasn't showing these messages.

I tried to run the install pip install data-utils displays the following message

ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=2.6,<=3.0; 0.0.2 Requires-Python >=2.6,<=3.0; 0.0.3 Requires-Python >=2.6,<=3.0; 0.0.4 Requires-Python >=2.6,<=3.0; 0.0.5 Requires-Python >=2.6,<=3.0; 0.0.6 Requires-Python >=2.6,<=3.0; 0.0.7 Requires-Python >=2.6,<=3.0
ERROR: Could not find a version that satisfies the requirement data-utils (from versions: none)
ERROR: No matching distribution found for data-utils

Have you ever had this kind of problem?

**Comment by pamelafox** [comment]
data_utils.py is a file in the same repo, so it should not be pip installed:

https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/scripts/data_utils.py


As for the DLL error, that looks to be an issue with your Window's installation of Numpy, see: https://stackoverflow.com/questions/65755148/how-to-fix-error-while-importing-numexpr-python

**Comment by edercarlima** [comment]
@davidm00 
This problem has already been resolved.
