### ISSUE TITLE
Create index to scanned pdf file

### ISSUE THREAD

**Issue by edercarlima** [microsoft/sample-app-aoai-chatGPT#240]
I'm trying to create an index using the script for a contract-type pdf file. This is a scanned contract containing contract information, a manual signature in pen and a notarized signature label.
When running the script, it displays the following message:

Created search index teste02
Chunking directory...
Total files to process=1 out of total directory size=1
Single process to chunk and parse the files. --njobs > 1 can help performance.
100%|██████████████████████████████████████ █████████ ████████████████████████████████████████ ██████████ █████████████████████████| 1/1 [00:00<?, ?it/s]
Traceback (most recent call last):
   File "C:\Projects\version0509\sample-app-aoai-chatGPT-main\scripts\data_preparation.py", line 424, in <module>
     create_index(index_config, credential, form_recognizer_client, embedding_model_endpoint=args.embedding_model_endpoint, use_layout=args.form_rec_use_layout, njobs=args.njobs)
   File "C:\Projects\version0509\sample-app-aoai-chatGPT-main\scripts\data_preparation.py", line 371, in create_index
     raise Exception("No chunks found. Please check the data path and chunk size.")
Exception: No chunks found. Please check the data path and chunk size.

I tried to create the index using this pdf file through Playground and I was unsuccessful. Through Playground, it does not display any error messages.

When using https://formrecognizer.appliedai.azure.com/studio?source=azureportal the Read option, the document was recognized. The information recognized was: contract documents, the client's manual signature and the data from the notary's recognition label.

Could you help me with this doubt?

**Comment by satarupaguha11** [comment]
Thanks for reaching out. We would like to debug this. Is it possible to share the document (if not confidential)?
