### ISSUE TITLE
azd up fails with AzureDeveloperCliCredential.get_token failed

### ISSUE THREAD

**Issue by Roydon** [microsoft/sample-app-aoai-chatGPT#323]
I am trying to deploy this app using `azd` cli following instructions provided in `README_azd.md` 
But getting following error

```
Running "auth_init.py"
Creating application registration
AzureDeveloperCliCredential.get_token failed: {"type":"consoleMessage","timestamp":"2023-10-17T16:00:38.120732-03:00","data":{"message":"resolving the Azure Directory from system environment (AZURE_SUBSCRIPTION_ID): failed to resolve user access to subscription with ID '54####51a-****-****-b067-*******'. If you recently gained access to this subscription, run `azd auth login` again to reload subscriptions.\nOtherwise, visit this subscription in Azure Portal using the browser, then run `azd auth login` \n"}}

Traceback (most recent call last):
  File "/Users/user/Projects/sample-app-aoai-chatGPT/.venv/lib/python3.11/site-packages/azure/identity/_credentials/azd_cli.py", line 220, in _run_command
    return subprocess.check_output(args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'azd auth token --output json --scope https://graph.microsoft.com/.default']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Projects/sample-app-aoai-chatGPT/./scripts/auth_init.py", line 86, in <module>
    app_id, client_id = create_application(credential)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Projects/sample-app-aoai-chatGPT/./scripts/auth_init.py", line 31, in create_application
    headers=get_auth_headers(credential),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Projects/sample-app-aoai-chatGPT/./scripts/auth_init.py", line 11, in get_auth_headers
    + credential.get_token("https://graph.microsoft.com/.default").token
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Projects/sample-app-aoai-chatGPT/.venv/lib/python3.11/site-packages/azure/identity/_internal/decorators.py", line 33, in wrapper
    token = fn(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Projects/sample-app-aoai-chatGPT/.venv/lib/python3.11/site-packages/azure/identity/_credentials/azd_cli.py", line 134, in get_token
    output = _run_command(command, self._process_timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Projects/sample-app-aoai-chatGPT/.venv/lib/python3.11/site-packages/azure/identity/_credentials/azd_cli.py", line 236, in _run_command
    raise ClientAuthenticationError(message=message) from ex
azure.core.exceptions.ClientAuthenticationError: {"type":"consoleMessage","timestamp":"2023-10-17T16:00:38.120732-03:00","data":{"message":"resolving the Azure Directory from system environment (AZURE_SUBSCRIPTION_ID): failed to resolve user access to subscription with ID '54####51a-****-****-b067-*******'. If you recently gained access to this subscription, run `azd auth login` again to reload subscriptions.\nOtherwise, visit this subscription in Azure Portal using the browser, then run `azd auth login` \n"}}


ERROR: failed running pre hooks: 'preprovision' hook failed with exit code: '1', Path: './scripts/auth_init.sh'. : exit code: 1
WARNING: your version of azd is out of date, you have 1.4.1 and the latest version is 1.4.2
```
I did run `azd auth login` and then `azd up` multiple times. 

What I am missing here ?

**Comment by marcusyatim** [comment]
Hi, may I ask how did you solve it? Thank you

**Comment by wtandler** [comment]
getting the same error.
