### ISSUE TITLE
Issue handling response back

### ISSUE THREAD

**Issue by balakreshnan** [microsoft/sample-app-aoai-chatGPT#349]
Here is the error i am getting after updating open ai library 0.28.1 and also latest code is breaking:

Traceback (most recent call last):
  File "C:\Code\chatapp\sample-app-aoai-chatGPT\app.py", line 237, in stream_with_data
    lineJson = formatApiResponseStreaming(rawResponse)
  File "C:\Code\chatapp\sample-app-aoai-chatGPT\app.py", line 332, in formatApiResponseStreaming
    "content": rawResponse["choices"][0]["delta"]["content"],
KeyError: 'delta'

used to work before.

**Comment by balakreshnan** [comment]
I try to correct the output schema and test still the page goes blank when we get streaming response.

**Comment by sarah-widder** [comment]
Hi @balakreshnan thanks for raising this issue, we will look into it. In the meantime you might try to downgrade the openai package to 0.27.7 or earlier.
