### ISSUE TITLE
On Azure deploy openai.error.InvalidRequestError occurs

### ISSUE THREAD

**Issue by lawiedc** [microsoft/sample-app-aoai-chatGPT#434]
When running with ./start.cmd, system works fully as expected. However, when deployed to azure, the response fails with errors as below.

I am setting the parameters in the .env file.  

I have tried using different values for AZURE_OPENAI_RESOURCE and ensuring that AZURE_OPENAI_MODEL and AZURE_OPENAI_MODEL_NAME are for deployed models on my resource.

The errors I am getting from the log stream are as follows. It looks like the system is not picking up any of the parameters, as the errors include conversation_without_data whether or not I have AZURE_SEARCH_SERVICE and AZURE_SEARCH_INDEX and AZURE_SEARCH_KEY set.

2023-12-05T12:15:11.200063599Z Traceback (most recent call last):
2023-12-05T12:15:11.200069000Z   File "/tmp/8dbf58b173460ca/app.py", line 541, in conversation_internal
2023-12-05T12:15:11.200074400Z     return conversation_without_data(request_body)
2023-12-05T12:15:11.200079400Z   File "/tmp/8dbf58b173460ca/app.py", line 494, in conversation_without_data
2023-12-05T12:15:11.200084600Z     response = openai.ChatCompletion.create(
2023-12-05T12:15:11.200089500Z   File "/tmp/8dbf58b173460ca/antenv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
2023-12-05T12:15:11.200094800Z     return super().create(*args, **kwargs)
2023-12-05T12:15:11.200099800Z   File "/tmp/8dbf58b173460ca/antenv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
2023-12-05T12:15:11.200105100Z     ) = cls.__prepare_create_request(
2023-12-05T12:15:11.200110000Z   File "/tmp/8dbf58b173460ca/antenv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 83, in __prepare_create_request
2023-12-05T12:15:11.200115100Z     raise error.InvalidRequestError(
2023-12-05T12:15:11.200120101Z openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>

**Comment by lawiedc** [comment]
From the first instruction in the README it looks like I should be editing app.py itself - but that doesn't seem right (and wasn't the way the code was working a few months ago)

**Update the environment variables listed in app.py**

**Comment by lawiedc** [comment]
Given all the environment parameters can now be managed directly via the "One Click Azure Deployment", I think this can be closed as no further action needed.

**Comment by lawiedc** [comment]
As above
