### ISSUE TITLE
An error occurred. Answers can't be saved at this time. If the problem persists, please contact the site administrator.

### ISSUE THREAD

**Issue by jainrahulsethi** [microsoft/sample-app-aoai-chatGPT#570]
After the response from the chat service, suddenly this error is generated. So, this particular interaction doesn't get saved in the cosmos db. Can someone point out the reason?

**Comment by jainrahulsethi** [comment]
Hey @sarah-widder :
It looks like this happen only for one particular user. Do i only set the debug log to true in the configuration and see the live logs too see what happens?
I feel it has something to do with cosmos db.. and also only for one particular user.. Can you throw some light?

**Comment by jainrahulsethi** [comment]
2024-02-07T10:25:19.9207353Z ERROR:root:Exception in /history/update
2024-02-07T10:25:19.9215573Z Traceback (most recent call last):
2024-02-07T10:25:19.9285175Z   File "/tmp/8dc27c358beac8d/app.py", line 696, in update_conversation
2024-02-07T10:25:19.9296551Z     cosmos_conversation_client.create_message(
2024-02-07T10:25:19.9305313Z   File "/tmp/8dc27c358beac8d/backend/history/cosmosdbservice.py", line 147, in create_message
2024-02-07T10:25:19.9313773Z     resp = self.container_client.upsert_item(message)
2024-02-07T10:25:19.9379712Z          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07T10:25:19.9390410Z   File "/tmp/8dc27c358beac8d/antenv/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
2024-02-07T10:25:19.9401960Z     return func(*args, **kwargs)
2024-02-07T10:25:19.9414054Z            ^^^^^^^^^^^^^^^^^^^^^
2024-02-07T10:25:19.9478226Z   File "/tmp/8dc27c358beac8d/antenv/lib/python3.11/site-packages/azure/cosmos/container.py", line 514, in upsert_item
2024-02-07T10:25:19.9487054Z     result = self.client_connection.UpsertItem(
2024-02-07T10:25:19.9495861Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07T10:25:19.9504144Z   File "/tmp/8dc27c358beac8d/antenv/lib/python3.11/site-packages/azure/cosmos/_cosmos_client_connection.py", line 1166, in UpsertItem
2024-02-07T10:25:19.9568842Z     return self.Upsert(document, path, "docs", collection_id, None, options, **kwargs)
2024-02-07T10:25:19.9579943Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07T10:25:19.9588469Z   File "/tmp/8dc27c358beac8d/antenv/lib/python3.11/site-packages/azure/cosmos/_cosmos_client_connection.py", line 2209, in Upsert
2024-02-07T10:25:19.9596811Z     result, self.last_response_headers = self.__Post(path, request_params, body, headers, **kwargs)
2024-02-07T10:25:19.9604918Z                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07T10:25:19.9671252Z   File "/tmp/8dc27c358beac8d/antenv/lib/python3.11/site-packages/azure/cosmos/_cosmos_client_connection.py", line 2342, in __Post
2024-02-07T10:25:19.9680027Z     return synchronized_request.SynchronizedRequest(
2024-02-07T10:25:19.9688185Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07T10:25:19.9697282Z   File "/tmp/8dc27c358beac8d/antenv/lib/python3.11/site-packages/azure/cosmos/_synchronized_request.py", line 206, in SynchronizedRequest
2024-02-07T10:25:19.9763753Z     return _retry_utility.Execute(
2024-02-07T10:25:19.9775238Z            ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07T10:25:19.9787077Z   File "/tmp/8dc27c358beac8d/antenv/lib/python3.11/site-packages/azure/cosmos/_retry_utility.py", line 83, in Execute
2024-02-07T10:25:19.9796304Z     result = ExecuteFunction(function, global_endpoint_manager, *args, **kwargs)
2024-02-07T10:25:19.9858003Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07T10:25:19.9868517Z   File "/tmp/8dc27c358beac8d/antenv/lib/python3.11/site-packages/azure/cosmos/_retry_utility.py", line 143, in ExecuteFunction
2024-02-07T10:25:19.9878489Z     return function(*args, **kwargs)
2024-02-07T10:25:19.9886583Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07T10:25:19.9952914Z   File "/tmp/8dc27c358beac8d/antenv/lib/python3.11/site-packages/azure/cosmos/_synchronized_request.py", line 154, in _Request
2024-02-07T10:25:19.9963641Z     raise exceptions.CosmosHttpResponseError(message=data, response=response)
2024-02-07T10:25:19.9972326Z azure.cosmos.exceptions.CosmosHttpResponseError: (BadRequest) Message: {"Errors":["The input name '' is invalid. Ensure to provide a unique non-empty string less than '1024' characters."]}
2024-02-07T10:25:19.9981184Z ActivityId: 0ea79db3-4f93-416a-a70a-57a92a851e67, Request URI: /apps/624f7e1a-2111-4194-abb4-42e4a8f8db50/services/42a2b7f4-e70b-46da-9c3a-db2cf79cfcfe/partitions/332154d6-c3b8-41f3-9989-507a900a5ae4/replicas/133512591025657007p, RequestStats:
2024-02-07T10:25:19.9989379Z RequestStartTime: 2024-02-07T10:25:13.9919059Z, RequestEndTime: 2024-02-07T10:25:13.9928737Z,  Number of regions attempted:1
2024-02-07T10:25:20.0058144Z {"systemHistory":[{"dateUtc":"2024-02-07T10:24:20.0262373Z","cpu":0.334,"memory":630456488.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0574,"availableThreads":32764,"minThreads":64,"maxThreads":32767},"numberOfOpenTcpConnection":422},{"dateUtc":"2024-02-07T10:24:30.0362661Z","cpu":0.295,"memory":630487388.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0668,"availableThreads":32764,"minThreads":64,"maxThreads":32767},"numberOfOpenTcpConnection":424},{"dateUtc":"2024-02-07T10:24:40.0462780Z","cpu":1.010,"memory":630539556.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0269,"availableThreads":32764,"minThreads":64,"maxThreads":32767},"numberOfOpenTcpConnection":426},{"dateUtc":"2024-02-07T10:24:50.0563485Z","cpu":0.766,"memory":630584936.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0526,"availableThreads":32764,"minThreads":64,"maxThreads":32767},"numberOfOpenTcpConnection":427},{"dateUtc":"2024-02-07T10:25:00.0663032Z","cpu":0.264,"memory":630589604.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0428,"availableThreads":32764,"minThreads":64,"maxThreads":32767},"numberOfOpenTcpConnection":427},{"dateUtc":"2024-02-07T10:25:10.0763216Z","cpu":0.717,"memory":630579120.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0678,"availableThreads":32764,"minThreads":64,"maxThreads":32767},"numberOfOpenTcpConnection":427}]}
2024-02-07T10:25:20.0067535Z RequestStart: 2024-02-07T10:25:13.9919878Z; ResponseTime: 2024-02-07T10:25:13.9928737Z; StoreResult: StorePhysicalAddress: rntbd://10.0.2.51:14300/apps/624f7e1a-2111-4194-abb4-42e4a8f8db50/services/42a2b7f4-e70b-46da-9c3a-db2cf79cfcfe/partitions/332154d6-c3b8-41f3-9989-507a900a5ae4/replicas/133512591025657007p, LSN: 553, GlobalCommittedLsn: 553, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#553, UsingLocalLSN: False, TransportException: null, BELatencyMs: 0.305, ActivityId: 0ea79db3-4f93-416a-a70a-57a92a851e67, RetryAfterInMs: , ReplicaHealthStatuses: [(port: 14300 | status: Connected | lkt: 2/4/2024 10:41:20 AM)], TransportRequestTimeline: {"requestTimeline":[{"event": "Created", "startTimeUtc": "2024-02-07T10:25:13.9919887Z", "durationInMs": 0.0103},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2024-02-07T10:25:13.9919990Z", "durationInMs": 0.0018},{"event": "Pipelined", "startTimeUtc": "2024-02-07T10:25:13.9920008Z", "durationInMs": 0.0634},{"event": "Transit Time", "startTimeUtc": "2024-02-07T10:25:13.9920642Z", "durationInMs": 0.5689},{"event": "Received", "startTimeUtc": "2024-02-07T10:25:13.9926331Z", "durationInMs": 0.0819},{"event": "Completed", "startTimeUtc": "2024-02-07T10:25:13.9927150Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":1,"openConnections":1},"connectionStats":{"waitforConnectionInit":"False","callsPendingReceive":0,"lastSendAttempt":"2024-02-07T10:25:13.9815505Z","lastSend":"2024-02-07T10:25:13.9815837Z","lastReceive":"2024-02-07T10:25:13.9850616Z"},"requestSizeInBytes":861,"requestBodySizeInBytes":296,"responseMetadataSizeInBytes":184,"responseBodySizeInBytes":117};
2024-02-07T10:25:20.0076455Z  ResourceType: Document, OperationType: Upsert
2024-02-07T10:25:20.0085388Z , SDK: Microsoft.Azure.Documents.Common/2.14.0
2024-02-07T10:25:20.0150581Z Code: BadRequest
2024-02-07T10:25:20.0159482Z Message: Message: {"Errors":["The input name '' is invalid. Ensure to provide a unique non-empty string less than '1024' characters."]}

This is the detail of the error

**Comment by Ra1257** [comment]
Hi, are you able to fix this issue? I am now experiencing the same problem with all users. The only recent change is that we added a custom domain to the web app.

**Comment by sarah-widder** [comment]
Hi @Ra1257 @jainrahulsethi this should have been fixed by #623
