### ISSUE TITLE
Internal Server Error from Azure App Service

### ISSUE THREAD

**Issue by AliKemalSahin** [microsoft/sample-app-aoai-chatGPT#587]
Hi, i'm trying to pull this repository from azure app service in deployment center but when i go to the app service link it's giving "internal server error". Is this general problem? @sarah-widder 

<img width="821" alt="Screen Shot 2024-02-05 at 11 28 36" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/49462856/7ef5dd83-69ca-41fc-a970-d517fb99e43e">
<img width="728" alt="Screen Shot 2024-02-05 at 11 29 03" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/49462856/afa1a0de-f20f-4114-b625-a3c86729368c">

**Comment by nrobert** [comment]
Suggestion: add the capture of the "logs" tab of "Deployment center" menu, it will display which version of the repo you are using.

On my side, I deployed a new web app this morning, it was ok. Here is my version:
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/6305666/fced0e15-7520-4f51-907b-5bcde15f2584)

**Comment by AliKemalSahin** [comment]
@nrobert 
I think it is same version but i dont get it why i'm getting this error :/ 

<img width="1366" alt="image" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/49462856/2233b934-de1e-4e08-83ab-13b8c162c0c3">

**Comment by AliKemalSahin** [comment]
I have one more app service who is the old one but it's working. As i noticed, this have different version, i guess there are something change in repository.

<img width="1186" alt="image" src="https://github.com/microsoft/sample-app-aoai-chatGPT/assets/49462856/4991c858-f159-4e65-805f-5563b7df5179">

**Comment by nrobert** [comment]
Already deployed apps will not automatically update to the latest commit from the selected branch (_main_ branch here), so that's normal that your old app is still there and working.

For the newest one, do you have any details in the 'log stream' tab?

**Comment by AliKemalSahin** [comment]
Yes it seems there are some python errors. But I can't say I know about Python. @nrobert 


2024-02-05T16:02:04  Welcome, you are now connected to log-streaming service.
Starting Log Tail -n 10 of existing logs ----/appsvctmp/volatile/logs/runtime/6e6f0ad73b9d63aafa6b89c0d1167340a14168fd8d3124e2f73b1e29183e1821.log
2024-02-05T15:42:57.232974125Z: [ERROR]  DEBUG:appsvc_profiler.installer:Code Profiler Installer is exiting as installation is completed
2024-02-05T15:42:57.236976570Z: [ERROR]  [2024-02-05 15:42:57 +0000] [79] [ERROR] Error handling request /robots933456.txt
2024-02-05T15:42:57.236993270Z: [ERROR]  Traceback (most recent call last):
2024-02-05T15:42:57.236996770Z: [ERROR]    File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
2024-02-05T15:42:57.236999970Z: [ERROR]      self.handle_request(listener, req, client, addr)
2024-02-05T15:42:57.237002470Z: [ERROR]    File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2024-02-05T15:42:57.237005270Z: [ERROR]      respiter = self.wsgi(environ, resp.start_response)
2024-02-05T15:42:57.237007970Z: [ERROR]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-05T15:42:57.237010770Z: [ERROR]  TypeError: Quart.__call__() missing 1 required positional argument: 'send'
2024-02-05T15:42:57.237567776Z: [INFO]  169.254.131.1 - - [05/Feb/2024:15:42:57 +0000] "GET /robots933456.txt HTTP/1.1" 500 0 "-" "-"/appsvctmp/volatile/logs/runtime/0be8fbe1ddc2a390405f8e4f2cce216c241b30946bee81cd3f028bf4b4530b4d.log
2024-02-05T15:53:10.577891843Z: [INFO]  169.254.131.1 - - [05/Feb/2024:15:53:10 +0000] "GET / HTTP/1.1" 500 0 "-" "-"
2024-02-05T15:57:44.332371819Z: [ERROR]  [2024-02-05 15:57:44 +0000] [79] [ERROR] Error handling request /
2024-02-05T15:57:44.332423420Z: [ERROR]  Traceback (most recent call last):
2024-02-05T15:57:44.332432720Z: [ERROR]    File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
2024-02-05T15:57:44.332439420Z: [ERROR]      self.handle_request(listener, req, client, addr)
2024-02-05T15:57:44.332445220Z: [ERROR]    File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2024-02-05T15:57:44.332476120Z: [ERROR]      respiter = self.wsgi(environ, resp.start_response)
2024-02-05T15:57:44.332482121Z: [ERROR]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-05T15:57:44.332487421Z: [ERROR]  TypeError: Quart.__call__() missing 1 required positional argument: 'send'
2024-02-05T15:57:44.332598522Z: [INFO]  169.254.131.1 - - [05/Feb/2024:15:57:44 +0000] "GET / HTTP/1.1" 500 0 "-" "-"/appsvctmp/volatile/logs/runtime/03152862709f97ec1fef3d1dee541083831e4924cd3a18e46ff1a3b400ec52e2.log
2024-02-05T15:42:54.104613818Z: [INFO]  Updated CA certificatesEnding Log Tail of existing logs ---Starting Live Log Stream ---

**Comment by nrobert** [comment]
Can you try to set "python3 -m gunicorn app:app" in the Startup command in the configuration?

Here:
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/6305666/a6ed55d9-e36d-4f2e-8ddf-84dd30789a21)

**Comment by AliKemalSahin** [comment]
Thanks so much for your support @nrobert  I added the command as you said and it was resolved :)

**Comment by nrobert** [comment]
You're welcome, I'm also struggling with run issues with it today and with dockerized version, and there may be other things that should be fixed soon - trying to figure them out to make the appropriate pull request
