### ISSUE TITLE
gunicorn error on webapp startup

### ISSUE THREAD

**Issue by jkingdon-ms** [microsoft/sample-app-aoai-chatGPT#606]
**Describe the bug**

Seeing this is the App Service Log Stream after deploying to Azure from my machine:

2024-02-10T03:04:29.689701450Z Traceback (most recent call last):
2024-02-10T03:04:29.689704850Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
2024-02-10T03:04:29.689708050Z     self.handle_request(listener, req, client, addr)
2024-02-10T03:04:29.689711050Z   File "/opt/python/3.11.4/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2024-02-10T03:04:29.689714250Z     respiter = self.wsgi(environ, resp.start_response)
2024-02-10T03:04:29.689717350Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-10T03:04:29.689720950Z TypeError: Quart.__call__() missing 1 required positional argument: 'send'

**To Reproduce**
1. run `az webapp up --runtime PYTHON:3.11 --sku B1 --name placeholder-service-123 --resource-group placeholder-rg --location eastus2 --subscription abc123`
2. Deployment completes
3. Observe Log Stream with Error aforementioned
4. Navigate to 'https://placeholder-service-123.azurewebsites.net/' and see 'Internal Server Error'

**Expected behavior**
1. run `az webapp up --runtime PYTHON:3.11 --sku B1 --name placeholder-service-123 --resource-group placeholder-rg --location eastus2 --subscription abc123`
2. Deployment completes
3. Observe Log Stream with no Errors
4. Navigate to 'https://placeholder-service-123.azurewebsites.net/' and see chatbot site

**Configuration: Please provide the following**
 - Azure OpenAI model name: gpt-4 
 - Azure OpenAI model version: 1106-Preview
 - Is chat history enabled? No
 - Are you using data? No

**Comment by beplay** [comment]
Maybe linked to #578 ?

**Comment by QuentinAd** [comment]
Related to #578 and #600 and #602

**Comment by jkingdon-ms** [comment]
This seems mostly related to #578

**Comment by sarah-widder** [comment]
@jkingdon-ms does setting the startup command like below resolve the issue?
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/19666316/8bc63b4f-7b66-414c-8a26-3541da6fc8c0)

**Comment by jkingdon-ms** [comment]
it does solve that particular problem, thanks @sarah-widder . though now i am seeing a different issue where none of my env vars defined in `.env` are included in the deployment.
