### ISSUE TITLE
Internal Server Error - Favicon

### ISSUE THREAD

**Issue by vickman1** [microsoft/sample-app-aoai-chatGPT#645]
**Describe the bug**
Deployment on Azure after syncing with Main leads to error:
2024-02-22T21:27:15.788917787Z: [ERROR]  TypeError: Quart.__call__() missing 1 required positional argument: 'send'
2024-02-22T21:27:15.792839923Z: [INFO]  169.254.129.5 - - [22/Feb/2024:21:27:15 +0000] "GET / HTTP/1.1" 500 0 "-" "-"
2024-02-22T21:27:15.839837254Z: [ERROR]  [2024-02-22 21:27:15 +0000] [71] [ERROR] Error handling request /favicon.ico
2024-02-22T21:27:15.839907555Z: [ERROR]  Traceback (most recent call last):
2024-02-22T21:27:15.839917955Z: [ERROR]    File "/tmp/8dc33ecb64edae2/antenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
2024-02-22T21:27:15.839922355Z: [ERROR]      self.handle_request(listener, req, client, addr)
2024-02-22T21:27:15.839926155Z: [ERROR]    File "/tmp/8dc33ecb64edae2/antenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2024-02-22T21:27:15.839930255Z: [ERROR]      respiter = self.wsgi(environ, resp.start_response)
2024-02-22T21:27:15.839933955Z: [ERROR]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T21:27:15.839937555Z: [ERROR]  TypeError: Quart.__call__() missing 1 required positional argument: 'send'
2024-02-22T21:27:15.845996111Z: [INFO]  169.254.129.5 - - [22/Feb/2024:21:27:15 +0000] "GET /favicon.ico HTTP/1.1" 500 0 "-" "-"
2024-02-22T21:28:57  No new trace in the past 1 min(s).
2024-02-22T21:29:57  No new trace in the past 2 min(s).

![Screenshot 2024-02-22 at 4 29 15 PM](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/135162496/f2968a69-2265-4d61-bbb0-79b0e3d57646)

**Comment by npsquared** [comment]
@vickman1 how are you deploying the app? Perhaps related to this [#578](https://github.com/microsoft/sample-app-aoai-chatGPT/issues/578)

**Comment by vickman1** [comment]
I think you're right, it was related to #578 
i noticed however, that when i placed UI custom variables in the app configuration - it is unable to locate the files

i simply replaced the Contoso.svg to myfilename.svg and its unable to find the file, even though its in my repository in the exact same location as Contoso.svg and i also placed in static assets folder and static folder just in case I missed other references. 

where are the UI variable files ideally located?

**Comment by vickman1** [comment]
issue was resolved via #578 as well as the startup command was incorrect as i was behind by a few changes to repo.

thank you all for help. 
i have figured out the image reference issue as well.
