### ISSUE TITLE
Error after deploying with "az webapp up": Quart.__call__() missing 1 required positional argument: 'send'

### ISSUE THREAD

**Issue by pm-itia** [microsoft/sample-app-aoai-chatGPT#650]
**Describe the bug**
I used this sample repository to deploy the chat web app using "Chat with your data" feature. I configured the variables in the .env file. I used the approach for deploying the app to an existing web app. The deployment resulted in 500 Internal Server Error (in the browser) and with the Type Error (in the Log stream in Azure).

**To Reproduce**
1. Update the .env file according to the instructions to use your own Azure OpenAI and Azure AI Search instances, deployment and index.
2. Start the app with `start.cmd` to verify it's configured correctly.
3. In case the web app has already existed, use the following commands in Power Shell or CMD (my SKU is B1 and runtime is Python:3.11):
```
az webapp config appsettings set -g <resource-group-name> -n <existing-app-name> --settings WEBSITE_WEBDEPLOY_USE_SCM=false
az webapp up --runtime <runtime-stack> --sku <sku> --name <existing-app-name> --resource-group <resource-group-name>
```
4. When the deployment is finished, open the web app in the URL - you should see the "Internal Server Error" message.
5. Go to the web app in Azure portal, open the Log stream to see the following error:

```
2024-02-26T07:22:23.522612043Z: [ERROR]  TypeError: Quart.__call__() missing 1 required positional argument: 'send'
2024-02-26T07:22:23.629793064Z: [ERROR]  [2024-02-26 07:22:23 +0000] [76] [ERROR] Error handling request /favicon.ico
2024-02-26T07:22:23.629832665Z: [ERROR]  Traceback (most recent call last):
2024-02-26T07:22:23.629838765Z: [ERROR]    File "/tmp/8dc3606dc6d13bd/antenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
2024-02-26T07:22:23.629842165Z: [ERROR]      self.handle_request(listener, req, client, addr)
2024-02-26T07:22:23.629845065Z: [ERROR]    File "/tmp/8dc3606dc6d13bd/antenv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2024-02-26T07:22:23.629848565Z: [ERROR]      respiter = self.wsgi(environ, resp.start_response)
2024-02-26T07:22:23.629851665Z: [ERROR]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-26T07:22:23.629854365Z: [ERROR]  TypeError: Quart.__call__() missing 1 required positional argument: 'send'
```

**Expected behavior**
The web app interface should appear, exactly the same as when the app is started locally.

**Configuration: Please provide the following**
 - Azure OpenAI model name and version: gpt-35-turbo-16k, version 0613
 - Is chat history enabled? No
 - Are you using data? Yes, Azure AI Search

**Additional context**
I observed that after these steps not only does the deployment fail and result in Internal Server Error, but also it blocks other deployments options - e.g., I was trying the deploy a chat app with the same configuration using Azure OpenAI Studio and the UI showed the message the deployment finished successfully, but it took about 30 seconds (much less time than expected) and opening the app in the browser still resulted in Internal Server Error. Can this be caused by setting  the WEBSITE_WEBDEPLOY_USE_SCM=false in step 3?

**Comment by alexander-croner-lindab** [comment]
I'm having the exactly same issue...! Pretty much same setup though i have chat history enabled and running standard gpt4

**Comment by tariromukute** [comment]
I'm experiencing the same issue. As a temporary solution, I've resorted to using the Docker approach for my app service. I was able to build the Docker app and publish it successfully.

**Comment by sarah-widder** [comment]
Hi @pm-itia @alexander-croner-lindab @tariromukute please see #657, you need to configure the startup command on the app to `python3 -m gunicorn app:app`. You can do this via `az webapp config set` or in the Azure Portal.

**Comment by alexander-croner-lindab** [comment]
Yep, saw that a little while later. Thanks! :)
