### ISSUE TITLE
Role error in Contoso related to change in line 823 of app.py

### ISSUE THREAD

**Issue by squla-dude** [microsoft/sample-app-aoai-chatGPT#773]
**Describe the bug**
Every message to a contoso bot beyond the first message leads to an error that simple says "role". 

The error is related to commit ee70ad0 from 3 days ago. Line 823 of app.py adds a list comprehension with a conditional on the message's 'role' parameter not being equal to 'tool'. I suspect that the role parameter is missing from some message objects or this equality can't be evaluated in some cases.

**To Reproduce**
1. Go to 'Azure AI Studio'
2. Click on 'Chat completions'
3. Deploy a bot on the basic tier in Sweden Central
4. Send a first message, the bot will respond correctly
5. Send a second message and the bot will display a red Error box with the word "role" in it. 

**Expected behavior**
A continued conversation for the 2nd message on

**Screenshots**
![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/10808631/80889cea-f451-4eba-8b5f-01f8c21676f4)

**Configuration: Please provide the following**
 - Azure OpenAI model name and version: gpt-4, Model Version 0613
 - Is chat history enabled? -- No
 - Are you using data? -- No data, only system prompts

**Additional context**
The log readout:

2024-04-12T13:16:12.177695867Z: [ERROR]  KeyError: 'role'Ending Log Tail of existing logs ---Starting Live Log Stream ---
2024-04-12T13:21:16.145135087Z: [ERROR]  ERROR:root:'role'
2024-04-12T13:21:16.187304909Z: [ERROR]  Traceback (most recent call last):
2024-04-12T13:21:16.187325209Z: [ERROR]    File "/tmp/8dc5a3527c6412f/app.py", line 865, in conversation_internal
2024-04-12T13:21:16.187329409Z: [ERROR]      result = await stream_chat_request(request_body)
2024-04-12T13:21:16.187332609Z: [ERROR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-12T13:21:16.187335809Z: [ERROR]    File "/tmp/8dc5a3527c6412f/app.py", line 852, in stream_chat_request
2024-04-12T13:21:16.187339309Z: [ERROR]      response = await send_chat_request(request_body)
2024-04-12T13:21:16.187342509Z: [ERROR]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-12T13:21:16.187345609Z: [ERROR]    File "/tmp/8dc5a3527c6412f/app.py", line 823, in send_chat_request
2024-04-12T13:21:16.187349110Z: [ERROR]      filtered_messages = [message for message in request['messages'] if message['role'] != 'tool']
2024-04-12T13:21:16.187352710Z: [ERROR]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-12T13:21:16.187356010Z: [ERROR]    File "/tmp/8dc5a3527c6412f/app.py", line 823, in <listcomp>
2024-04-12T13:21:16.187359710Z: [ERROR]      filtered_messages = [message for message in request['messages'] if message['role'] != 'tool']
2024-04-12T13:21:16.187363010Z: [ERROR]                                                                         ~~~~~~~^^^^^^^^

**Comment by Schoemann** [comment]
awesome thanks
