### ISSUE TITLE
commit 6163da3 introduces an IndentationError in backend/utils.py

### ISSUE THREAD

**Issue by bartallan** [microsoft/sample-app-aoai-chatGPT#813]
**Describe the bug**
The [latest commit](https://github.com/microsoft/sample-app-aoai-chatGPT/commit/6163da3acbe0abe7801fc55c33e0bc0063da4042)  introduced a breaking change - in this case a simple indentation error on line 160 of the backend/utils.py file

**To Reproduce**
1. Start the app

**Expected behavior**
The app should run without throwing Exceptions

**Screenshots**

![image](https://github.com/microsoft/sample-app-aoai-chatGPT/assets/117774637/db8e228a-2357-455d-9a75-29168d292e24)

**Comment by lizylgit** [comment]
Web App fails as of today with ":( Application Error". This was working couple of days ago.  Could someone please help fix them. Thanks
These below error in the diagnostic console (same bug as reported above, by bartallan) :  
----
024-04-25T02:48:10.233879177Z Traceback (most recent call last):
2024-04-25T02:48:10.233916678Z   File "/tmp/8dc64d1293f5ce8/antenv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2024-04-25T02:48:10.233935478Z     worker.init_process()
2024-04-25T02:48:10.233939978Z   File "/tmp/8dc64d1293f5ce8/antenv/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
2024-04-25T02:48:10.233943678Z     super(UvicornWorker, self).init_process()
2024-04-25T02:48:10.233947678Z   File "/tmp/8dc64d1293f5ce8/antenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
2024-04-25T02:48:10.233951178Z     self.load_wsgi()
2024-04-25T02:48:10.233954478Z   File "/tmp/8dc64d1293f5ce8/antenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2024-04-25T02:48:10.233957978Z     self.wsgi = self.app.wsgi()
2024-04-25T02:48:10.233961178Z                 ^^^^^^^^^^^^^^^
2024-04-25T02:48:10.233964578Z   File "/tmp/8dc64d1293f5ce8/antenv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-04-25T02:48:10.233967978Z     self.callable = self.load()
2024-04-25T02:48:10.233971278Z                     ^^^^^^^^^^^
2024-04-25T02:48:10.233974478Z   File "/tmp/8dc64d1293f5ce8/antenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2024-04-25T02:48:10.233977978Z     return self.load_wsgiapp()
2024-04-25T02:48:10.233981278Z            ^^^^^^^^^^^^^^^^^^^
2024-04-25T02:48:10.233984678Z   File "/tmp/8dc64d1293f5ce8/antenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-04-25T02:48:10.233988178Z     return util.import_app(self.app_uri)
2024-04-25T02:48:10.233991478Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-25T02:48:10.233994778Z   File "/tmp/8dc64d1293f5ce8/antenv/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
2024-04-25T02:48:10.233998278Z     mod = importlib.import_module(module)
2024-04-25T02:48:10.234001578Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-25T02:48:10.234004878Z   File "/opt/python/3.11.8/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-04-25T02:48:10.234008378Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-04-25T02:48:10.234011679Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-25T02:48:10.234015179Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-04-25T02:48:10.234019079Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-04-25T02:48:10.234022479Z   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-04-25T02:48:10.234025979Z   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-04-25T02:48:10.234029379Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-04-25T02:48:10.243780083Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-04-25T02:48:10.243805084Z   File "/tmp/8dc64d1293f5ce8/app.py", line 23, in <module>
2024-04-25T02:48:10.243810784Z     from backend.utils import (
2024-04-25T02:48:10.243814084Z   File "/tmp/8dc64d1293f5ce8/backend/utils.py", line 171
2024-04-25T02:48:10.243817384Z     response_obj = {
2024-04-25T02:48:10.243820484Z                     ^
2024-04-25T02:48:10.243823784Z IndentationError: unindent does not match any outer indentation level
2024-04-25T02:48:10.243826984Z [2024-04-25 02:48:10 +0000] [72] [INFO] Worker exiting (pid: 72)
2024-04-25T02:48:10.243853984Z [2024-04-25 02:48:10 +0000] [74] [ERROR] Exception in worker process

**Comment by lizylgit** [comment]
This codebase is linked to Azure AI Studio playground, which cannot be modified by the user. To make this codebase reliable, please could commits be pushed to main branch, only when the CI /CD Test has passed.  For ex. the Test failed with 'IndentaionError' still the changes were commited to the main branch -> https://github.com/microsoft/sample-app-aoai-chatGPT/actions/runs/8822569021/job/24221071386 
Thanks

**Comment by bjornarfjelldal** [comment]
This causes default web apps from (in my case) Azure AI to fail, with, as per @lizylgit, no possibility for us to fix.

Its worrysome that this can occur in your Azure OpenAI Studio default GUI setup without getting caught. Hope that you can fix it asap as we rely on being able to deploy and share our models.

**Comment by abhahn** [comment]
Hi everyone, thanks for raising the issue, and sorry for the sudden breakage.  A recent commit has fixed this issue, but I realize the urgent need for additional safeguards for our CI process to ensure that simple things like this don't break users of the app.  I'm going to prioritize adding some additional steps to our CI process today.

For now I will close the issue, but please feel free to reopen if you think there is still a problem.
